### ISSUE TITLE
python2.7 __future__ annotations problem

### ISSUE THREAD

**Issue by tanjiaxin** [xZise/flake8-future-import#21]
In python 2.7 it will check annotations import, but in python2.7 try to import annotations from __future__ it will report 
`from __future__ import annotations`
`SyntaxError: future feature annotations is not defined (<input>, line 1)`
Is there a way to solve this problem by flake8 setting not by ignoring it?
Also found a error code problem in https://pypi.org/project/flake8-future-import/  the annotations's code should be FI18, in the page it is FI12.
![image](https://user-images.githubusercontent.com/15188761/63159413-1a231680-c04e-11e9-9ea1-cad30d18a0b6.png)

**Comment by xZise** [comment]
Hi, sorry for the delay. Now if I'm not mistaken, you need to specify a `--min-version`. In that case it won't report missing imports, which aren't supported with that version.

Feel free to reopen the issue when this doesn't actually solve your problem.

The spelling mistake on pypi is unfortunate, because I haven't seen a possibility to update the text there without uploading a new version. Now the original file it is using is already fixed with #20 by @dgw, so an update should fix that mistake on pypi.
